name: Check arXiv papers
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: BuildAction
        run: |
          npm ci
          npm run-script build

      - name: Tweet
        uses: ./.github/actions/TweetAction
        with:
          twi-cons-key: ${{ secrets.TWITTERCONSUMERKEY }}
          twi-cons-secret: ${{ secrets.TWITTERCONSUMERSECRET }}
          twi-token-key: ${{ secrets.TWITTERTOKENKEY }}
          twi-token-secret: ${{ secrets.TWITTERTOKENSECRET }}
